# Generated by Django 2.2 on 2023-11-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogpost_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='auth',
            field=models.CharField(default='dell', max_length=120),
        ),
    ]
